var data2 = [
  {
    "district":"Balaghat1",
    "area":"9,229"
  },
  {
    "district":"Barwani",
    "area":"5,422"
  },
  {
    "district":"BetulT",
    "area":"10,043"
  },
  {
    "district":"Bhind",
    "area":"4,459"
  },
  {
    "district":"Bhopal",
    "area":"2,772"
  },
  {
    "district":"Chattarpur",
    "area":"8,687"
  },
  {
    "district":"Chhindwara1",
    "area":"11,815"
  },
  {
    "district":"Damoh",
    "area":"7,306"
  },
  {
    "district":"Datia",
    "area":"2,691"
  },
  {
    "district":"DewasT",
    "area":"7,020"
  },
  {
    "district":"Dindorf",
    "area":"7,470"
  },
  {
    "district":"EastNimar1",
    "area":"10,776"
  },
  {
    "district":"Guna",
    "area":"11,064"
  },
  {
    "district":"Gwalior",
    "area":"4,560"
  },
  {
    "district":"HardaT",
    "area":"3,330"
  },
  {
    "district":"Hoshangabad1",
    "area":"6,707"
  },
  {
    "district":"Indore",
    "area":"3,898"
  },
  {
    "district":"Jabalpur1",
    "area":"5,211"
  },
  {
    "district":"Jhabua1",
    "area":"6,778"
  },
  {
    "district":"Katni",
    "area":"4,950"
  },
  {
    "district":"Mandla1",
    "area":"5,800"
  },
  {
    "district":"Mandsaur",
    "area":"5,535"
  },
  {
    "district":"Morena1",
    "area":"4,989"
  },
  {
    "district":"Narsimhapur",
    "area":"5,133"
  },
  {
    "district":"Neemach",
    "area":"4,256"
  },
  {
    "district":"Panna",
    "area":"7,135"
  },
  {
    "district":"Raisen",
    "area":"8,466"
  },
  {
    "district":"Rajgarh",
    "area":"6,153"
  },
  {
    "district":"Ratlam1",
    "area":"4,861"
  },
  {
    "district":"Rewa",
    "area":"6,314"
  },
  {
    "district":"Sagar",
    "area":"10,252"
  },
  {
    "district":"Satna",
    "area":"7,502"
  },
  {
    "district":"Sehore",
    "area":"6,578"
  },
  {
    "district":"Seonf",
    "area":"8,758"
  },
  {
    "district":"Shahdol1",
    "area":"9,952"
  },
  {
    "district":"Shajapur",
    "area":"6,195"
  },
  {
    "district":"Sheopur",
    "area":"6,606"
  },
  {
    "district":"Shivpuri",
    "area":"10,277"
  },
  {
    "district":"SidhiT",
    "area":"10,526"
  },
  {
    "district":"Tikamgarh",
    "area":"5,048"
  },
  {
    "district":"Ujjain",
    "area":"6,091"
  },
  {
    "district":"Umaria",
    "area":"4,076"
  },
  {
    "district":"Vidisha",
    "area":"7,371"
  },
  {
    "district":"WestNimar1",
    "area":"8,030"
  }
];