var strVar = {
  "Overview": {
    "CommProd": "0000-1087-0000-0000",
    "ResDate": 20151003180400,
    "AgmtId": "ARG1234",
    "PoolName": "Root Pool",
    "NoOfLevels": 3,
    "Country": "SE",
    "BaseCcy": "HKD",
    "StartDt": 20150108,
    "YClsoingBal": -444000,
    "BookedBal": -344000,
    "ValDtBal": -444000,
    "ODLimit": 20000,
    "UsageRatio": 20000,
    "TotAvlBal": -444000,
    "CcyGrpBalance": [
      {
        "Ccy": "HKD",
        "poolbaseccy": "HKD",
        "BookedBalance": -720000,
        "ValueDatedBalance": -1020000,
        "Bookedpoolbaseccy": -720000,
        "ValueDatedBalancePoolBaseCcy": -720000
      }
    ],
    "ParticipantDtls": [
      {
        "PoolAcctNo": "107",
        "Country": "SE",
        "TP": "",
        "NickName": "Customer pool",
        "PoolAccountName": "Customer pool",
        "Ccy": "HKD",
        "Limit": 20000,
        "BookBal": -260000,
        "ValueBal": -340000,
        "FXRt": 1,
        "BookBalBaseCcy": -260000,
        "ValueBalBaseCcy": -340000,
        "Account": [
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          },
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          },
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          }
        ],
        "SubPool": [
          {
            "PoolAcctNo": "106",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool",
            "PoolAccountName": "Currency Pool",
            "Ccy": "HKD",
            "Limit": 20000,
            "BookBal": -140000,
            "ValueBal": -180000,
            "FXRt": 1,
            "BookBalBaseCcy": -140000,
            "ValueBalBaseCcy": -180000,
            "Account": [
              {
                "PoolAcctNo": "52801053236",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC2",
                "PoolAccountName": "New EOD ReWork ACC2",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              },
              {
                "PoolAcctNo": "52801049972",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC1",
                "PoolAccountName": "New EOD ReWork ACC1",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              }
            ],
            "SubPool": null
          },
          {
            "PoolAcctNo": "109",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool New",
            "PoolAccountName": "Currency Pool New",
            "Ccy": "GBP",
            "Limit": 20000,
            "BookBal": -90000,
            "ValueBal": -90000,
            "FXRt": 12.00248,
            "BookBalBaseCcy": -1080223.2,
            "ValueBalBaseCcy": -1080223.2,
            "Account": null,
            "SubPool": null
          },
          {
            "PoolAcctNo": "106",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool",
            "PoolAccountName": "Currency Pool",
            "Ccy": "HKD",
            "Limit": 20000,
            "BookBal": -140000,
            "ValueBal": -180000,
            "FXRt": 1,
            "BookBalBaseCcy": -140000,
            "ValueBalBaseCcy": -180000,
            "Account": [
              {
                "PoolAcctNo": "52801053236",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC2",
                "PoolAccountName": "New EOD ReWork ACC2",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              },
              {
                "PoolAcctNo": "52801049972",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC1",
                "PoolAccountName": "New EOD ReWork ACC1",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              }
            ],
            "SubPool": null
          },
          {
            "PoolAcctNo": "109",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool New",
            "PoolAccountName": "Currency Pool New",
            "Ccy": "GBP",
            "Limit": 20000,
            "BookBal": -90000,
            "ValueBal": -90000,
            "FXRt": 12.00248,
            "BookBalBaseCcy": -1080223.2,
            "ValueBalBaseCcy": -1080223.2,
            "Account": null,
            "SubPool": null
          }


        ]
      },
      {
        "PoolAcctNo": "110",
        "Country": "SE",
        "TP": "",
        "NickName": "Customer Pool New",
        "PoolAccountName": "Customer Pool New",
        "Ccy": "SEK",
        "Limit": 10000,
        "BookBal": -140000,
        "ValueBal": -140000,
        "FXRt": 1.07133,
        "BookBalBaseCcy": -149986.2,
        "ValueBalBaseCcy": -149986.2,
        "Account": null,
        "SubPool": null
      },
      {
        "PoolAcctNo": "107",
        "Country": "SE",
        "TP": "",
        "NickName": "Customer pool",
        "PoolAccountName": "Customer pool",
        "Ccy": "HKD",
        "Limit": 20000,
        "BookBal": -260000,
        "ValueBal": -340000,
        "FXRt": 1,
        "BookBalBaseCcy": -260000,
        "ValueBalBaseCcy": -340000,
        "Account": [
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          },
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          },
          {
            "PoolAcctNo": "52801053279",
            "Country": "HK",
            "TP": "N",
            "NickName": "New EOD ReWork ACC3",
            "PoolAccountName": "New EOD ReWork ACC3",
            "Ccy": "HKD",
            "Limit": 10000,
            "BookBal": -30000,
            "ValueBal": -70000,
            "FXRt": 1,
            "BookBalBaseCcy": -30000,
            "ValueBalBaseCcy": -70000
          }
        ],
        "SubPool": [
          {
            "PoolAcctNo": "106",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool",
            "PoolAccountName": "Currency Pool",
            "Ccy": "HKD",
            "Limit": 20000,
            "BookBal": -140000,
            "ValueBal": -180000,
            "FXRt": 1,
            "BookBalBaseCcy": -140000,
            "ValueBalBaseCcy": -180000,
            "Account": [
              {
                "PoolAcctNo": "52801053236",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC2",
                "PoolAccountName": "New EOD ReWork ACC2",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              },
              {
                "PoolAcctNo": "52801049972",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC1",
                "PoolAccountName": "New EOD ReWork ACC1",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              }
            ],
            "SubPool": null
          },
          {
            "PoolAcctNo": "109",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool New",
            "PoolAccountName": "Currency Pool New",
            "Ccy": "GBP",
            "Limit": 20000,
            "BookBal": -90000,
            "ValueBal": -90000,
            "FXRt": 12.00248,
            "BookBalBaseCcy": -1080223.2,
            "ValueBalBaseCcy": -1080223.2,
            "Account": null,
            "SubPool": null
          },
          {
            "PoolAcctNo": "106",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool",
            "PoolAccountName": "Currency Pool",
            "Ccy": "HKD",
            "Limit": 20000,
            "BookBal": -140000,
            "ValueBal": -180000,
            "FXRt": 1,
            "BookBalBaseCcy": -140000,
            "ValueBalBaseCcy": -180000,
            "Account": [
              {
                "PoolAcctNo": "52801053236",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC2",
                "PoolAccountName": "New EOD ReWork ACC2",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              },
              {
                "PoolAcctNo": "52801049972",
                "Country": "HK",
                "TP": "N",
                "NickName": "New EOD ReWork ACC1",
                "PoolAccountName": "New EOD ReWork ACC1",
                "Ccy": "HKD",
                "Limit": 10000,
                "BookBal": -70000,
                "ValueBal": -90000,
                "FXRt": 1,
                "BookBalBaseCcy": -70000,
                "ValueBalBaseCcy": -90000
              }
            ],
            "SubPool": null
          },
          {
            "PoolAcctNo": "109",
            "Country": "SE",
            "TP": "",
            "NickName": "Currency Pool New",
            "PoolAccountName": "Currency Pool New",
            "Ccy": "GBP",
            "Limit": 20000,
            "BookBal": -90000,
            "ValueBal": -90000,
            "FXRt": 12.00248,
            "BookBalBaseCcy": -1080223.2,
            "ValueBalBaseCcy": -1080223.2,
            "Account": null,
            "SubPool": null
          }


        ]
      },
      {
        "PoolAcctNo": "110",
        "Country": "SE",
        "TP": "",
        "NickName": "Customer Pool New",
        "PoolAccountName": "Customer Pool New",
        "Ccy": "SEK",
        "Limit": 10000,
        "BookBal": -140000,
        "ValueBal": -140000,
        "FXRt": 1.07133,
        "BookBalBaseCcy": -149986.2,
        "ValueBalBaseCcy": -149986.2,
        "Account": null,
        "SubPool": null
      }
    ],
    "Account": [
      {
        "PoolAcctNo": "52801053309",
        "Country": "HK",
        "TP": "N",
        "NickName": "New EOD ReWork ACC4",
        "PoolAccountName": "New EOD ReWork ACC4",
        "Ccy": "HKD",
        "Limit": 10000,
        "BookBal": -70000,
        "ValueBal": -90000,
        "FXRt": 1,
        "BookBalBaseCcy": -70000,
        "ValueBalBaseCcy": -90000
      },
       {
        "PoolAcctNo": "52801053309",
        "Country": "HK",
        "TP": "N",
        "NickName": "New EOD ReWork ACC4",
        "PoolAccountName": "New EOD ReWork ACC4",
        "Ccy": "HKD",
        "Limit": 10000,
        "BookBal": -70000,
        "ValueBal": -90000,
        "FXRt": 1,
        "BookBalBaseCcy": -70000,
        "ValueBalBaseCcy": -90000
      },
       {
        "PoolAcctNo": "52801053309",
        "Country": "HK",
        "TP": "N",
        "NickName": "New EOD ReWork ACC4",
        "PoolAccountName": "New EOD ReWork ACC4",
        "Ccy": "HKD",
        "Limit": 10000,
        "BookBal": -70000,
        "ValueBal": -90000,
        "FXRt": 1,
        "BookBalBaseCcy": -70000,
        "ValueBalBaseCcy": -90000
      }
    ]
  }
};